language: "python"
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install -r test-requirements.txt
  - python setup.py develop

before_script:
  make lint

script:
  # At the moment CI is only used to check unit tests
  # not functional / integration, which requires running
  # zimbra server
  python -m unittest tests.test_utils tests.test_zobjects
